#!/bin/bash

# number of infringements found
RESULT=0

echo -n "* Checking for avocadoserver imports from avocadoserver: "
LIST=`git grep -E '^(import avocadoserver\..*|from avocadoserver(.*)import)' avocadoserver`
COUNT=`git grep -E '^(import avocadoserver\..*|from avocadoserver(.*)import)' avocadoserver | wc -l`
(( RESULT = RESULT + COUNT ))
echo "$COUNT"
if [ -n "$LIST" ]; then
   echo "$LIST"
fi
unset LIST
unset COUNT

if [ "$RESULT" -ne 0 ]; then
    echo "ERROR: $RESULT module boundary infringements found"
else
    echo "PASS: no module boundary infringement(s) found"
fi
exit $RESULT
